import Foundation
import GRDB
import Testing
@testable import Actualist

/// The New Budget seed must be the schema a fresh Actual v26.9.0 budget holds
/// (fixture generated by `scripts/parity/new-budget-schema`), fully migrated,
/// and usable by every local write path that needs more than the starter tables.
struct NewBudgetStarterSchemaTests {
    private struct ColumnInfo: Decodable, Equatable {
        let name: String
        let type: String
        let notnull: Int
        let dflt_value: String?
        let pk: Int
    }

    private static var fixtureRoot: URL {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appending(path: "Fixtures/ActualCore26_9_0/NewBudget")
    }

    private func makeSeed(
        identityGenerator: @escaping @Sendable () -> String = { UUID().uuidString }
    ) throws -> (database: BudgetDatabase, url: URL) {
        let directory = FileManager.default.temporaryDirectory
            .appending(path: "NewBudgetSchema-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appending(path: "db.sqlite")
        let database = try BudgetDatabase.makeNewBudgetStarterDatabase(
            at: url,
            identityGenerator: identityGenerator
        )
        return (database, url)
    }

    @Test func seededTableInfoEqualsPinnedUpstreamSchema() throws {
        let expected = try JSONDecoder().decode(
            [String: [ColumnInfo]].self,
            from: Data(contentsOf: Self.fixtureRoot.appending(path: "starter-schema.json"))
        )
        #expect(expected.count == 33)
        let (_, url) = try makeSeed()
        let queue = try DatabaseQueue(path: url.path)
        try queue.read { db in
            for (table, columns) in expected {
                let actual = try Row.fetchAll(db, sql: "PRAGMA table_info(\"\(table)\")").map {
                    ColumnInfo(
                        name: $0["name"], type: $0["type"], notnull: $0["notnull"],
                        dflt_value: $0["dflt_value"], pk: $0["pk"]
                    )
                }
                #expect(actual == columns, "table_info differs for \(table)")
            }
        }
    }

    @Test func migrationIDsEqualUpstreamListAndAreAllApplied() throws {
        let listed = try String(
            contentsOf: Self.fixtureRoot.appending(path: "migrations.txt"), encoding: .utf8
        ).split(separator: "\n").compactMap { Int64($0) }
        #expect(listed.count == 59)
        #expect(Set(listed) == PortableBudgetSchema.knownMigrationIDs)
        let (_, url) = try makeSeed()
        let applied = try DatabaseQueue(path: url.path).read { db in
            try Int64.fetchAll(db, sql: "SELECT id FROM __migrations__ ORDER BY id")
        }
        #expect(applied == listed.sorted())
    }

    @Test func seedHoldsStarterRowsDashboardAndNoClockOrMeta() throws {
        let (_, url) = try makeSeed()
        try DatabaseQueue(path: url.path).read { db in
            func count(_ table: String) -> Int {
                ((try? Int.fetchOne(db, sql: "SELECT COUNT(*) FROM \(table)")) ?? nil) ?? -1
            }
            #expect(count("category_groups") == 3)
            #expect(count("categories") == 7)
            #expect(count("category_mapping") == 7)
            #expect(count("dashboard_pages") == 1)
            #expect(count("dashboard") == 12)
            #expect(count("accounts") == 0)
            #expect(count("__meta__") == 0)
            #expect(count("messages_clock") == 0)
            #expect(count("messages_crdt") == 0)
            let unmapped = try Int.fetchOne(
                db,
                sql: """
                    SELECT COUNT(*) FROM categories c
                    LEFT JOIN category_mapping m ON m.id = c.id AND m.transferId = c.id
                    WHERE m.id IS NULL
                    """
            )
            #expect(unmapped == 0)
            let orphans = try Int.fetchOne(
                db,
                sql: "SELECT COUNT(*) FROM dashboard WHERE dashboard_page_id NOT IN (SELECT id FROM dashboard_pages)"
            )
            #expect(orphans == 0)
        }
    }

    @Test func starterCategoriesReadBackThroughDatabase() async throws {
        let (database, _) = try makeSeed()
        let categories = try await database.fetchCategories()
        #expect(categories.map(\.name) == [
            "Food", "General", "Bills", "Bills (Flexible)", "Savings", "Income", "Starting Balances"
        ])
    }

    @Test func scheduleCreatePreferenceWriteAndSavedFilterSucceedOnFreshSeed() async throws {
        let (_, url) = try makeSeed()
        // Production reopens the seed with the node ID from its metadata.
        let database = try BudgetDatabase(databaseURL: url, localNodeID: "newbudgetnode")
        try await DatabaseQueue(path: url.path).write { db in
            try db.execute(sql: "INSERT INTO accounts (id, name) VALUES ('checking', 'Checking')")
        }

        let created = try await database.createSchedule(
            ScheduleCreateCommand(
                budgetID: "budget",
                identity: ScheduleCreateIdentity(scheduleID: "sched", ruleID: "sched-rule", nextDateID: "sched-next"),
                name: "Rent",
                definition: ScheduleDefinitionDraft(
                    accountID: "checking", payeeMappingID: nil, amount: .exact(-100),
                    dateRule: .oneTime(dayID: "2026-10-01", operation: "is")
                ),
                postsTransaction: false, customUpcomingLength: nil, asOfDayID: "2026-09-27"
            ),
            now: Date(timeIntervalSince1970: 1_790_000_000)
        )
        #expect(created.kind == .created)

        var preferenceBuilder = LocalFirstSyncMessageBuilder()
        let preference = try await database.setGlobalCategoryLearningMessages(
            enabled: false, builder: &preferenceBuilder
        )
        _ = try await database.commitUserAction(
            preference.messages,
            descriptor: .learningPref(LearningPrefActionDescriptor(after: false)),
            source: .ui
        )

        var filterBuilder = LocalFirstSyncMessageBuilder()
        let filter = try await database.createSavedTransactionFilter(
            id: "filter",
            draft: SavedTransactionFilterDraft(
                name: "Big",
                conditions: [RuleCondition(field: "account", operation: "is", value: .string("checking"), type: "id")],
                join: .and
            ),
            builder: &filterBuilder
        )
        #expect(filter.changed)

        let stored = try await DatabaseQueue(path: url.path).read { db in
            (
                try String.fetchOne(db, sql: "SELECT name FROM schedules WHERE id = 'sched'"),
                try String.fetchOne(db, sql: "SELECT value FROM preferences WHERE id = 'learn-categories'"),
                try String.fetchOne(db, sql: "SELECT name FROM transaction_filters WHERE id = 'filter'")
            )
        }
        #expect(stored.0 == "Rent")
        #expect(stored.1 == "false")
        #expect(stored.2 == "Big")
    }

    /// Writes the seed to a fixed path so the upstream loader can be run on the
    /// exact bytes this code produces (`run.sh check`, audit item 1.1).
    @Test func seedWrittenForUpstreamInterop() throws {
        let directory = FileManager.default.temporaryDirectory
            .appending(path: "actualist-newbudget-interop", directoryHint: .isDirectory)
        try? FileManager.default.removeItem(at: directory)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appending(path: "db.sqlite")
        _ = try BudgetDatabase.makeNewBudgetStarterDatabase(at: url)
        #expect(FileManager.default.fileExists(atPath: url.path))
    }
}
