#!/usr/bin/env python3
"""Write the Swift starter-schema source from generated schema.sql and seed rows.

usage: emit_swift.py <schema.sql> <seed-rows.json> <ActualStarterSchema.swift>
"""
import json
import sys
from pathlib import Path

sql = Path(sys.argv[1]).read_text()
seed = json.load(open(sys.argv[2]))
if '"""' in sql or "\\" in sql:
    sys.exit("schema.sql contains characters the raw literal cannot hold")
(page,) = seed["dashboard_pages"]


def literal(value):
    if value is None:
        return "nil"
    if '"###' in value:
        sys.exit("dashboard value cannot be held by a raw literal")
    return '###"' + value + '"###'


widgets = "".join(
    f"        ({literal(w['type'])}, {w['width']}, {w['height']}, {w['x']}, {w['y']}, {literal(w['meta'])}),\n"
    for w in sorted(seed["dashboard"], key=lambda w: (w["y"], w["x"]))
)
out = f'''// GENERATED by scripts/parity/new-budget-schema (run.sh emit-swift) from the
// schema a fresh Actual v26.9.0 budget (59fe126f) holds after createBudget and
// migrate(). Do not edit by hand. Actual is MIT licensed; see
// THIRD_PARTY_NOTICES.md.

import Foundation

enum ActualStarterSchema {{
    /// Tables and indexes in upstream creation order. No views or triggers:
    /// Actual regenerates its `v_*` views when `__meta__.view-hash` is absent.
    static let sql = #"""
{sql}"""#

    /// The "Main" dashboard page seeded by the JS migrations. Upstream
    /// generates the page and widget ids at runtime; Actualist does the same.
    static let dashboardPageName = "{page["name"]}"

    /// Seeded dashboard widgets: type, width, height, x, y, meta.
    static let dashboardWidgets: [(type: String, width: Int, height: Int, x: Int, y: Int, meta: String?)] = [
{widgets}    ]
}}
'''
Path(sys.argv[3]).write_text(out)
