// GENERATED by scripts/parity/new-budget-schema (run.sh emit-swift) from the
// schema a fresh Actual v26.9.0 budget (59fe126f) holds after createBudget and
// migrate(). Do not edit by hand. Actual is MIT licensed; see
// THIRD_PARTY_NOTICES.md.

import Foundation

enum ActualStarterSchema {
    /// Tables and indexes in upstream creation order. No views or triggers:
    /// Actual regenerates its `v_*` views when `__meta__.view-hash` is absent.
    static let sql = #"""
CREATE TABLE pending_transactions
  (id TEXT PRIMARY KEY,
   acct INTEGER,
   amount INTEGER,
   description TEXT,
   date TEXT,
   FOREIGN KEY(acct) REFERENCES accounts(id));
CREATE TABLE created_budgets (month TEXT PRIMARY KEY);
CREATE TABLE __migrations__ (id INT PRIMARY KEY NOT NULL);
CREATE TABLE banks
 (id TEXT PRIMARY KEY,
  bank_id TEXT,
  name TEXT,
  tombstone INTEGER DEFAULT 0);
CREATE TABLE accounts
   (id TEXT PRIMARY KEY,
    account_id TEXT,
    name TEXT,
    balance_current INTEGER,
    balance_available INTEGER,
    balance_limit INTEGER,
    mask TEXT,
    official_name TEXT,
    subtype TEXT,
    bank TEXT,
    offbudget INTEGER DEFAULT 0,
    closed INTEGER DEFAULT 0,
    tombstone INTEGER DEFAULT 0, sort_order REAL, type TEXT, account_sync_source TEXT, last_sync text, last_reconciled text, bank_sync_status text, account_group_id TEXT DEFAULT NULL);
CREATE TABLE category_mapping
  (id TEXT PRIMARY KEY,
   transferId TEXT);
CREATE TABLE transactions
  (id TEXT PRIMARY KEY,
   isParent INTEGER DEFAULT 0,
   isChild INTEGER DEFAULT 0,
   acct TEXT,
   category TEXT,
   amount INTEGER,
   description TEXT,
   notes TEXT,
   date INTEGER,
   financial_id TEXT,
   type TEXT,
   location TEXT,
   error TEXT,
   imported_description TEXT,
   starting_balance_flag INTEGER DEFAULT 0,
   transferred_id TEXT,
   sort_order REAL,
   tombstone INTEGER DEFAULT 0, cleared INTEGER DEFAULT 1, pending INTEGER DEFAULT 0, parent_id TEXT, schedule TEXT, reconciled INTEGER DEFAULT 0, raw_synced_data text);
CREATE TABLE messages_crdt
 (id INTEGER PRIMARY KEY,
  timestamp TEXT NOT NULL UNIQUE,
  dataset TEXT NOT NULL,
  row TEXT NOT NULL,
  column TEXT NOT NULL,
  value BLOB NOT NULL);
CREATE TABLE messages_clock (id INTEGER PRIMARY KEY, clock TEXT);
CREATE TABLE categories
 (id TEXT PRIMARY KEY,
  name TEXT,
  is_income INTEGER DEFAULT 0,
  cat_group TEXT,
  sort_order REAL,
  tombstone INTEGER DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0, goal_def TEXT DEFAULT null, template_settings JSON DEFAULT '{"source": "notes"}', cleanup_def TEXT DEFAULT NULL);
CREATE TABLE payees
  (id TEXT PRIMARY KEY,
   name TEXT,
   category TEXT,
   tombstone INTEGER DEFAULT 0,
   transfer_acct TEXT, favorite INTEGER DEFAULT 0 DEFAULT FALSE, learn_categories BOOLEAN DEFAULT 1);
CREATE TABLE payee_mapping
  (id TEXT PRIMARY KEY,
   targetId TEXT);
CREATE TABLE category_groups
   (id TEXT PRIMARY KEY,
    name TEXT,
    is_income INTEGER DEFAULT 0,
    sort_order REAL,
    tombstone INTEGER DEFAULT 0, hidden BOOLEAN NOT NULL DEFAULT 0);
CREATE TABLE rules
  (id TEXT PRIMARY KEY,
   stage TEXT,
   conditions TEXT,
   actions TEXT,
   tombstone INTEGER DEFAULT 0, conditions_op TEXT DEFAULT 'and');
CREATE TABLE __meta__ (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE schedules
  (id TEXT PRIMARY KEY,
   rule TEXT,
   active INTEGER DEFAULT 0,
   completed INTEGER DEFAULT 0,
   posts_transaction INTEGER DEFAULT 0,
   tombstone INTEGER DEFAULT 0, name TEXT DEFAULT NULL, custom_upcoming_length TEXT DEFAULT NULL, sort_order REAL DEFAULT 0);
CREATE TABLE schedules_next_date
  (id TEXT PRIMARY KEY,
   schedule_id TEXT,
   local_next_date INTEGER,
   local_next_date_ts INTEGER,
   base_next_date INTEGER,
   base_next_date_ts INTEGER, tombstone INTEGER DEFAULT 0);
CREATE TABLE schedules_json_paths
  (schedule_id TEXT PRIMARY KEY,
   payee TEXT,
   account TEXT,
   amount TEXT,
   date TEXT);
CREATE TABLE zero_budget_months
  (id TEXT PRIMARY KEY,
   buffered INTEGER DEFAULT 0);
CREATE TABLE zero_budgets
  (id TEXT PRIMARY KEY,
   month INTEGER,
   category TEXT,
   amount INTEGER DEFAULT 0,
   carryover INTEGER DEFAULT 0, goal INTEGER DEFAULT null, long_goal INTEGER DEFAULT null);
CREATE TABLE reflect_budgets
  (id TEXT PRIMARY KEY,
   month INTEGER,
   category TEXT,
   amount INTEGER DEFAULT 0,
   carryover INTEGER DEFAULT 0, goal INTEGER DEFAULT null, long_goal INTEGER DEFAULT null);
CREATE TABLE notes
  (id TEXT PRIMARY KEY,
   note TEXT);
CREATE TABLE kvcache (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE kvcache_key (id INTEGER PRIMARY KEY, key REAL);
CREATE INDEX trans_category_date ON transactions(category, date);
CREATE INDEX trans_category ON transactions(category);
CREATE INDEX trans_date ON transactions(date);
CREATE INDEX trans_parent_id ON transactions(parent_id);
CREATE INDEX trans_sorted ON transactions(date desc, starting_balance_flag, sort_order desc, id);
CREATE INDEX messages_crdt_search ON messages_crdt(dataset, row, column, timestamp);
CREATE TABLE transaction_filters
  (id TEXT PRIMARY KEY,
   name TEXT,
   conditions TEXT,
   conditions_op TEXT DEFAULT 'and',
   tombstone INTEGER DEFAULT 0);
CREATE TABLE custom_reports
  (
    id TEXT PRIMARY KEY,
    name TEXT,
    start_date TEXT,
    end_date TEXT,
    date_static INTEGER DEFAULT 0,
    date_range TEXT,
    mode TEXT DEFAULT 'total',
    group_by TEXT DEFAULT 'Category',
    balance_type TEXT DEFAULT 'Expense',
    show_empty INTEGER DEFAULT 0,
    show_offbudget INTEGER DEFAULT 0,
    show_hidden INTEGER DEFAULT 0,
    show_uncategorized INTEGER DEFAULT 0,
    selected_categories TEXT,
    graph_type TEXT DEFAULT 'BarGraph',
    conditions TEXT,
    conditions_op TEXT DEFAULT 'and',
    metadata TEXT,
    interval TEXT DEFAULT 'Monthly',
    color_scheme TEXT,
    tombstone INTEGER DEFAULT 0
  , include_current INTEGER DEFAULT 0, sort_by TEXT DEFAULT 'desc', trim_intervals INTEGER DEFAULT 0, show_trend_lines INTEGER DEFAULT 0);
CREATE TABLE dashboard
        (id TEXT PRIMARY KEY,
         type TEXT,
         width INTEGER,
         height INTEGER,
         x INTEGER,
         y INTEGER,
         meta TEXT,
         tombstone INTEGER DEFAULT 0, dashboard_page_id TEXT);
CREATE TABLE preferences
       (id TEXT PRIMARY KEY,
        value TEXT);
CREATE TABLE tags(
  id TEXT PRIMARY KEY,
  tag TEXT UNIQUE,
  color TEXT,
  description TEXT
, tombstone integer DEFAULT 0, hidden BOOLEAN DEFAULT 0);
CREATE TABLE dashboard_pages
        (id TEXT PRIMARY KEY,
         name TEXT,
         tombstone INTEGER DEFAULT 0);
CREATE TABLE payee_locations (
      id TEXT PRIMARY KEY,
      payee_id TEXT,
      latitude REAL,
      longitude REAL,
      created_at INTEGER,
      tombstone INTEGER DEFAULT 0
    );
CREATE INDEX idx_payee_locations_payee_id ON payee_locations (payee_id);
CREATE INDEX idx_payee_locations_tombstone_payee_created ON payee_locations (tombstone, payee_id, created_at);
CREATE INDEX idx_payee_locations_geo_tombstone ON payee_locations (tombstone, latitude, longitude);
CREATE TABLE cleanup_groups
  (id TEXT PRIMARY KEY,
   name TEXT NOT NULL,
   tombstone INTEGER DEFAULT 0);
CREATE INDEX idx_transactions_acct_tombstone ON transactions(acct, tombstone);
CREATE INDEX idx_transactions_schedule ON transactions(schedule);
CREATE TABLE account_groups
  (id TEXT PRIMARY KEY,
   name TEXT,
   sort_order REAL,
   tombstone INTEGER DEFAULT 0);
"""#

    /// The "Main" dashboard page seeded by the JS migrations. Upstream
    /// generates the page and widget ids at runtime; Actualist does the same.
    static let dashboardPageName = "Main"

    /// Seeded dashboard widgets: type, width, height, x, y, meta.
    static let dashboardWidgets: [(type: String, width: Int, height: Int, x: Int, y: Int, meta: String?)] = [
        (###"summary-card"###, 3, 2, 0, 0, ###"{"name":"Total Income (YTD)","content":"{\"type\":\"sum\",\"fontSize\":20}","timeFrame":{"start":"2024-01-01","end":"2024-12-31","mode":"yearToDate"},"conditions":[{"field":"amount","op":"gt","value":0},{"field":"account","op":"onBudget","value":""},{"field":"transfer","op":"is","value":false}],"conditionsOp":"and"}"###),
        (###"summary-card"###, 3, 2, 3, 0, ###"{"name":"Total Expenses (YTD)","content":"{\"type\":\"sum\",\"fontSize\":20}","timeFrame":{"start":"2024-01-01","end":"2024-12-31","mode":"yearToDate"},"conditions":[{"field":"amount","op":"lt","value":0},{"field":"account","op":"onBudget","value":""},{"field":"transfer","op":"is","value":false}],"conditionsOp":"and"}"###),
        (###"summary-card"###, 3, 2, 6, 0, ###"{"name":"Avg Per Month","content":"{\"type\":\"avgPerMonth\",\"fontSize\":20}","timeFrame":{"start":"2024-01-01","end":"2024-12-31","mode":"yearToDate"},"conditions":[{"field":"amount","op":"lt","value":0},{"field":"account","op":"onBudget","value":""},{"field":"transfer","op":"is","value":false}],"conditionsOp":"and"}"###),
        (###"summary-card"###, 3, 2, 9, 0, ###"{"name":"Avg Per Transaction","content":"{\"type\":\"avgPerTransact\",\"fontSize\":20}","timeFrame":{"start":"2024-01-01","end":"2024-12-31","mode":"yearToDate"},"conditions":[{"field":"amount","op":"lt","value":0},{"field":"account","op":"onBudget","value":""},{"field":"transfer","op":"is","value":false}],"conditionsOp":"and"}"###),
        (###"net-worth-card"###, 6, 2, 0, 2, nil),
        (###"cash-flow-card"###, 6, 2, 6, 2, nil),
        (###"spending-card"###, 4, 2, 0, 5, ###"{"name":"This Month","mode":"single-month"}"###),
        (###"spending-card"###, 4, 2, 4, 5, ###"{"name":"Budget Overview","mode":"budget"}"###),
        (###"spending-card"###, 4, 2, 8, 5, ###"{"name":"3-Month Average","mode":"average"}"###),
        (###"calendar-card"###, 8, 4, 0, 8, ###"{"name":"Transaction Calendar","timeFrame":{"start":"2024-01-01","end":"2024-03-31","mode":"sliding-window"},"conditions":[{"field":"transfer","op":"is","value":false}],"conditionsOp":"and"}"###),
        (###"summary-card"###, 4, 2, 8, 8, ###"{"name":"Recent Net Worth Change","content":"{\"type\":\"sum\",\"fontSize\":32}","timeFrame":{"start":"2024-01-01","end":"2024-03-31","mode":"sliding-window"},"conditions":[],"conditionsOp":"and"}"###),
        (###"markdown-card"###, 4, 2, 8, 10, ###"{"content":"## Dashboard Tips\n\nYou can add new widgets or edit existing widgets by using the buttons at the top of the page. Choose a widget type and customize it to fit your needs.\n\n**Moving cards:** Drag any card by its header to reposition it.\n\n**Deleting cards:** Click the three-dot menu on any card and select \"Remove\"."}"###),
    ]
}
