import Foundation
import GRDB

/// Fresh-budget bootstrap. Pinned Actual `createBudget` copies its bundled
/// `default-db.sqlite` and `loadBudget` runs `migrate()` over it. This owner
/// builds the same end state without those bytes: the DDL a fresh Actual
/// v26.9.0 budget holds (`ActualStarterSchema`, generated by
/// `scripts/parity/new-budget-schema`; Actual is MIT, see
/// `THIRD_PARTY_NOTICES.md`), every migration id in `__migrations__` so Actual
/// treats the file as fully migrated, the seeded dashboard, and the frozen
/// starter projection (three category groups, seven categories with their
/// `category_mapping` rows, zero accounts, zero CRDT messages). `__meta__` and
/// `messages_clock` stay empty: Actual recreates the view hash and the clock
/// when it loads the file.
///
/// Every starter row ID is generated at runtime. Actual's seed UUIDs are
/// generator output, not stable contracts, and are never copied. The
/// projection's group and category order is the observed starter structure,
/// not an alphabetical sort; `sort_order` values are generated fresh and
/// unique across the projection because the seed's values are not unique
/// within a group and display order cannot be derived from them.
extension BudgetDatabase {
    /// Creates a new starter database at `databaseURL` and returns it opened.
    /// `identityGenerator` supplies every starter row ID; production uses
    /// UUIDs and tests pass a deterministic sequence.
    static func makeNewBudgetStarterDatabase(
        at databaseURL: URL,
        identityGenerator: @escaping @Sendable () -> String = { UUID().uuidString }
    ) throws -> BudgetDatabase {
        let queue = try DatabaseQueue(path: databaseURL.path)
        try queue.write { db in
            try db.execute(sql: ActualStarterSchema.sql)
            for migrationID in PortableBudgetSchema.knownMigrationIDs.sorted() {
                try db.execute(sql: "INSERT INTO __migrations__ (id) VALUES (?)", arguments: [migrationID])
            }
            try insertNewBudgetDashboard(db: db, identityGenerator: identityGenerator)
            try insertNewBudgetStarterRows(db: db, identityGenerator: identityGenerator)
        }
        return try BudgetDatabase(databaseURL: databaseURL)
    }

    // The frozen starter projection: group name, income flag, and the group's
    // categories in observed order. Deliberately not alphabetical, and the
    // category lists are not derived from the seed's shared sort_order values.
    private static let newBudgetStarterGroups: [(name: String, isIncome: Bool, categories: [String])] = [
        (name: "Usual Expenses", isIncome: false, categories: ["Food", "General", "Bills", "Bills (Flexible)"]),
        (name: "Investments and Savings", isIncome: false, categories: ["Savings"]),
        (name: "Income", isIncome: true, categories: ["Income", "Starting Balances"])
    ]

    private static func insertNewBudgetStarterRows(
        db: Database,
        identityGenerator: @Sendable () -> String
    ) throws {
        var groupOrder = 0.0
        // One continuously increasing counter, so every starter row carries a
        // distinct display order — the seed's shared `sort_order` values are
        // never reproduced.
        var categoryOrder = 0.0
        for group in newBudgetStarterGroups {
            let groupID = identityGenerator()
            groupOrder += ActualSortOrder.increment
            try db.execute(
                sql: """
                    INSERT INTO category_groups (id, name, is_income, hidden, tombstone, sort_order)
                    VALUES (?, ?, ?, 0, 0, ?)
                    """,
                arguments: [groupID, group.name, group.isIncome, groupOrder]
            )
            for categoryName in group.categories {
                let categoryID = identityGenerator()
                categoryOrder += ActualSortOrder.increment
                try db.execute(
                    sql: """
                        INSERT INTO categories (id, name, cat_group, is_income, hidden, tombstone, sort_order)
                        VALUES (?, ?, ?, ?, 0, 0, ?)
                        """,
                    arguments: [categoryID, categoryName, groupID, group.isIncome, categoryOrder]
                )
                try db.execute(
                    sql: "INSERT INTO category_mapping (id, transferId) VALUES (?, ?)",
                    arguments: [categoryID, categoryID]
                )
            }
        }
    }

    private static func insertNewBudgetDashboard(
        db: Database,
        identityGenerator: @Sendable () -> String
    ) throws {
        let pageID = identityGenerator()
        try db.execute(
            sql: "INSERT INTO dashboard_pages (id, name) VALUES (?, ?)",
            arguments: [pageID, ActualStarterSchema.dashboardPageName]
        )
        for widget in ActualStarterSchema.dashboardWidgets {
            try db.execute(
                sql: """
                    INSERT INTO dashboard (id, type, width, height, x, y, meta, dashboard_page_id)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                arguments: [identityGenerator(), widget.type, widget.width, widget.height, widget.x, widget.y, widget.meta, pageID]
            )
        }
    }
}
